# Generates de/doc/toc.yml from doc/toc.yml: the same structure, German names from
# tools/Translate/toc.de.json (English name kept when no translation exists) and hrefs
# pointing at the German page when one exists, otherwise at the English page on
# docs.timecockpit.com with the suffix " (EN)". Runs before every build (build.ps1).
# Do not edit de/doc/toc.yml by hand; edit doc/toc.yml or toc.de.json instead.

[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
. (Join-Path $PSScriptRoot "translate-common.ps1")

$names = @{}
$namesFile = Join-Path $PSScriptRoot "toc.de.json"
if (Test-Path -LiteralPath $namesFile) {
    $json = Get-Content -LiteralPath $namesFile -Raw -Encoding UTF8 | ConvertFrom-Json
    foreach ($p in $json.PSObject.Properties) { if ($p.Name -ne '_comment') { $names[$p.Name] = $p.Value } }
}
$map = Get-DePageMap
$toc = Read-Toc (Join-Path $script:RepoRoot "doc\toc.yml")

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("# Generated by tools/Translate/build-de-toc.ps1 from doc/toc.yml and toc.de.json. Do not edit.")
$translated = 0
$fallback = 0

function Write-Node($node, [int]$level) {
    $indent = '  ' * $level
    foreach ($item in $node.Items) {
        $name = if ($names.ContainsKey($item.Name)) { $names[$item.Name] } else { $item.Name }
        $href = $null
        if ($item.Href) {
            $enPath = "doc/$($item.Href)"
            if ($map.ContainsKey($enPath)) {
                $href = $map[$enPath].Substring(4)   # strip "doc/"
                $script:translated++
            }
            else {
                $href = "https://docs.timecockpit.com/doc/" + ($item.Href -replace '\.md$', '.html')
                $name = "$name (EN)"
                $script:fallback++
            }
        }
        $quoted = '"' + ($name -replace '\\', '\\' -replace '"', '\"') + '"'
        [void]$sb.AppendLine("$indent- name: $quoted")
        if ($href) { [void]$sb.AppendLine("$indent  href: $href") }
        if ($item.Items.Count -gt 0) {
            [void]$sb.AppendLine("$indent  items:")
            Write-Node $item ($level + 1)
        }
    }
}
Write-Node $toc 0

$out = Join-Path $script:DeRoot "doc\toc.yml"
[System.IO.File]::WriteAllText($out, $sb.ToString(), (New-Object System.Text.UTF8Encoding $false))
Write-Host "build-de-toc: de/doc/toc.yml written, $translated German pages, $fallback entries link to the English site"
