# Builds tools/Translate/glossary.de.md: the curated documentation terms from
# glossary.curated.de.md followed by every short EN/DE UI label of the time cockpit web
# client, taken from the product's i18n files. Re-run when the product texts change.
#
# Sources (TimeCockpit monorepo next to this repo, adjust -ProductRoot if needed):
#   web/Source/CockpitFramework.Web.UI.Angular/libs/cofx/assets/i18n/messages-cofx.json
#   web/Source/CockpitFramework.Web.UI.Angular/libs/time-cockpit-calendar/assets/i18n/messages-tc.json
# Each leaf is { "en": "...", "de": "..." }. Only labels up to 6 words without HTML or
# placeholders are taken over; sentences and messages are not glossary material.

[CmdletBinding()]
param(
    [string]$ProductRoot = ""
)

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
if (-not $ProductRoot) { $ProductRoot = Join-Path (Resolve-Path (Join-Path $scriptDir "..\..\..")).Path "TimeCockpit" }
$sources = @(
    "web\Source\CockpitFramework.Web.UI.Angular\libs\cofx\assets\i18n\messages-cofx.json",
    "web\Source\CockpitFramework.Web.UI.Angular\libs\time-cockpit-calendar\assets\i18n\messages-tc.json"
)

$pairs = @{}
function Walk($node) {
    if ($null -eq $node) { return }
    if ($node -is [System.Management.Automation.PSCustomObject]) {
        $props = $node.PSObject.Properties
        $en = $props['en']; $de = $props['de']
        if ($en -and $de -and ($en.Value -is [string]) -and ($de.Value -is [string])) {
            $e = $en.Value.Trim(); $d = $de.Value.Trim()
            if ($e -and $d -and $e -ne $d -and $e -notmatch '<|{{|\{\d|\n' -and $d -notmatch '<|{{|\{\d|\n' -and ($e -split '\s+').Count -le 6 -and $e -notmatch '[.!?]$') {
                $key = $e.ToLowerInvariant()
                if (-not $pairs.ContainsKey($key)) { $pairs[$key] = [pscustomobject]@{ En = $e; De = $d } }
            }
            return
        }
        foreach ($p in $props) { Walk $p.Value }
    }
}

foreach ($rel in $sources) {
    $file = Join-Path $ProductRoot $rel
    if (-not (Test-Path -LiteralPath $file)) { Write-Warning "source not found: $file"; continue }
    Walk (Get-Content -LiteralPath $file -Raw -Encoding UTF8 | ConvertFrom-Json)
}

$curated = Join-Path $scriptDir "glossary.curated.de.md"
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("# Glossary EN -> DE for the time cockpit documentation")
[void]$sb.AppendLine()
[void]$sb.AppendLine("Generated by ``build-glossary.ps1``: the curated part comes from ``glossary.curated.de.md`` (edit there), the UI labels from the product's i18n files. Curated terms win over UI labels.")
[void]$sb.AppendLine()
if (Test-Path -LiteralPath $curated) {
    [void]$sb.AppendLine((Get-Content -LiteralPath $curated -Raw -Encoding UTF8).TrimEnd())
    [void]$sb.AppendLine()
}
[void]$sb.AppendLine("## UI labels of the web client (generated)")
[void]$sb.AppendLine()
[void]$sb.AppendLine("| English | German |")
[void]$sb.AppendLine("|---|---|")
foreach ($p in ($pairs.Values | Sort-Object En)) {
    [void]$sb.AppendLine("| $($p.En -replace '\|', '\|') | $($p.De -replace '\|', '\|') |")
}
$out = Join-Path $scriptDir "glossary.de.md"
[System.IO.File]::WriteAllText($out, $sb.ToString(), (New-Object System.Text.UTF8Encoding $false))
Write-Host "glossary.de.md: $($pairs.Keys.Count) UI labels"
