### YamlMime:ManagedReference
items:
- uid: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement
  commentId: T:TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement
  id: ExternalTypeConfigurationElement
  parent: TimeCockpit.Data.Extensibility
  children:
  - TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.#ctor
  - TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.AssemblyName
  - TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.AssemblyPath
  - TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.Name
  - TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.Namespace
  - TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.TypeName
  langs:
  - csharp
  - vb
  name: ExternalTypeConfigurationElement
  nameWithType: ExternalTypeConfigurationElement
  fullName: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement
  type: Class
  source:
    path: TimeCockpit.Data
    isExternal: true
  assemblies:
  - TimeCockpit.Data
  namespace: TimeCockpit.Data.Extensibility
  summary: "\nA class that represents an external assembly to load\n"
  syntax:
    content: 'public class ExternalTypeConfigurationElement : ConfigurationElement'
    content.vb: >-
      Public Class ExternalTypeConfigurationElement
          Inherits ConfigurationElement
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.#ctor
  commentId: M:TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.#ctor
  id: '#ctor'
  parent: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement
  langs:
  - csharp
  - vb
  name: ExternalTypeConfigurationElement()
  nameWithType: ExternalTypeConfigurationElement.ExternalTypeConfigurationElement()
  fullName: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.ExternalTypeConfigurationElement()
  type: Constructor
  source:
    path: TimeCockpit.Data
    isExternal: true
  assemblies:
  - TimeCockpit.Data
  namespace: TimeCockpit.Data.Extensibility
  syntax:
    content: public ExternalTypeConfigurationElement()
    content.vb: Public Sub New
  overload: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.Name
  commentId: P:TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.Name
  id: Name
  parent: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: ExternalTypeConfigurationElement.Name
  fullName: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.Name
  type: Property
  source:
    path: TimeCockpit.Data
    isExternal: true
  assemblies:
  - TimeCockpit.Data
  namespace: TimeCockpit.Data.Extensibility
  summary: "\nGets the name of the entry.\n"
  syntax:
    content: public string Name { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Name As String
  overload: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.Name*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.TypeName
  commentId: P:TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.TypeName
  id: TypeName
  parent: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement
  langs:
  - csharp
  - vb
  name: TypeName
  nameWithType: ExternalTypeConfigurationElement.TypeName
  fullName: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.TypeName
  type: Property
  source:
    path: TimeCockpit.Data
    isExternal: true
  assemblies:
  - TimeCockpit.Data
  namespace: TimeCockpit.Data.Extensibility
  summary: "\nGets the type name.\n"
  syntax:
    content: public string TypeName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property TypeName As String
  overload: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.TypeName*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.Namespace
  commentId: P:TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.Namespace
  id: Namespace
  parent: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement
  langs:
  - csharp
  - vb
  name: Namespace
  nameWithType: ExternalTypeConfigurationElement.Namespace
  fullName: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.Namespace
  type: Property
  source:
    path: TimeCockpit.Data
    isExternal: true
  assemblies:
  - TimeCockpit.Data
  namespace: TimeCockpit.Data.Extensibility
  summary: "\nGets the type name.\n"
  syntax:
    content: public string Namespace { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Namespace As String
  overload: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.Namespace*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.AssemblyPath
  commentId: P:TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.AssemblyPath
  id: AssemblyPath
  parent: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement
  langs:
  - csharp
  - vb
  name: AssemblyPath
  nameWithType: ExternalTypeConfigurationElement.AssemblyPath
  fullName: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.AssemblyPath
  type: Property
  source:
    path: TimeCockpit.Data
    isExternal: true
  assemblies:
  - TimeCockpit.Data
  namespace: TimeCockpit.Data.Extensibility
  summary: "\nGets the assembly path.\n"
  syntax:
    content: public string AssemblyPath { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property AssemblyPath As String
  overload: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.AssemblyPath*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.AssemblyName
  commentId: P:TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.AssemblyName
  id: AssemblyName
  parent: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement
  langs:
  - csharp
  - vb
  name: AssemblyName
  nameWithType: ExternalTypeConfigurationElement.AssemblyName
  fullName: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.AssemblyName
  type: Property
  source:
    path: TimeCockpit.Data
    isExternal: true
  assemblies:
  - TimeCockpit.Data
  namespace: TimeCockpit.Data.Extensibility
  summary: "\nGets the name of the assembly.\n"
  syntax:
    content: public string AssemblyName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property AssemblyName As String
  overload: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.AssemblyName*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: TimeCockpit.Data.Extensibility
  commentId: N:TimeCockpit.Data.Extensibility
  isExternal: true
  name: TimeCockpit.Data.Extensibility
  nameWithType: TimeCockpit.Data.Extensibility
  fullName: TimeCockpit.Data.Extensibility
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.#ctor*
  commentId: Overload:TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.#ctor
  isExternal: true
  name: ExternalTypeConfigurationElement
  nameWithType: ExternalTypeConfigurationElement.ExternalTypeConfigurationElement
  fullName: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.ExternalTypeConfigurationElement
- uid: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.Name*
  commentId: Overload:TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.Name
  isExternal: true
  name: Name
  nameWithType: ExternalTypeConfigurationElement.Name
  fullName: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.TypeName*
  commentId: Overload:TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.TypeName
  isExternal: true
  name: TypeName
  nameWithType: ExternalTypeConfigurationElement.TypeName
  fullName: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.TypeName
- uid: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.Namespace*
  commentId: Overload:TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.Namespace
  isExternal: true
  name: Namespace
  nameWithType: ExternalTypeConfigurationElement.Namespace
  fullName: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.Namespace
- uid: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.AssemblyPath*
  commentId: Overload:TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.AssemblyPath
  isExternal: true
  name: AssemblyPath
  nameWithType: ExternalTypeConfigurationElement.AssemblyPath
  fullName: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.AssemblyPath
- uid: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.AssemblyName*
  commentId: Overload:TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.AssemblyName
  isExternal: true
  name: AssemblyName
  nameWithType: ExternalTypeConfigurationElement.AssemblyName
  fullName: TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement.AssemblyName
