### YamlMime:ManagedReference
items:
- uid: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection
  commentId: T:TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection
  id: ExternalTypesConfigurationElementCollection
  parent: TimeCockpit.Data.Extensibility
  children:
  - TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.#ctor
  - TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.CreateNewElement
  - TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  langs:
  - csharp
  - vb
  name: ExternalTypesConfigurationElementCollection
  nameWithType: ExternalTypesConfigurationElementCollection
  fullName: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection
  type: Class
  source:
    path: TimeCockpit.Data
    isExternal: true
  assemblies:
  - TimeCockpit.Data
  namespace: TimeCockpit.Data.Extensibility
  summary: "\nRepresents a collection of <xref href=\"TimeCockpit.Data.Extensibility.ExternalTypeConfigurationElement\" data-throw-if-not-resolved=\"false\"></xref>\n"
  syntax:
    content: 'public class ExternalTypesConfigurationElementCollection : ConfigurationElementCollection'
    content.vb: >-
      Public Class ExternalTypesConfigurationElementCollection
          Inherits ConfigurationElementCollection
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.CreateNewElement
  commentId: M:TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.CreateNewElement
  id: CreateNewElement
  parent: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection
  langs:
  - csharp
  - vb
  name: CreateNewElement()
  nameWithType: ExternalTypesConfigurationElementCollection.CreateNewElement()
  fullName: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.CreateNewElement()
  type: Method
  source:
    path: TimeCockpit.Data
    isExternal: true
  assemblies:
  - TimeCockpit.Data
  namespace: TimeCockpit.Data.Extensibility
  summary: "\nWhen overridden in a derived class, creates a new <xref href=\"System.Configuration.ConfigurationElement\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  syntax:
    content: protected override ConfigurationElement CreateNewElement()
    return:
      type: System.Configuration.ConfigurationElement
      description: "\nA new <xref href=\"System.Configuration.ConfigurationElement\" data-throw-if-not-resolved=\"false\"></xref>.\n"
    content.vb: Protected Overrides Function CreateNewElement As ConfigurationElement
  overload: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.CreateNewElement*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  commentId: M:TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  id: GetElementKey(System.Configuration.ConfigurationElement)
  parent: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection
  langs:
  - csharp
  - vb
  name: GetElementKey(ConfigurationElement)
  nameWithType: ExternalTypesConfigurationElementCollection.GetElementKey(ConfigurationElement)
  fullName: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  type: Method
  source:
    path: TimeCockpit.Data
    isExternal: true
  assemblies:
  - TimeCockpit.Data
  namespace: TimeCockpit.Data.Extensibility
  summary: "\nGets the element key for a specified configuration element when overridden in a derived class.\n"
  syntax:
    content: protected override object GetElementKey(ConfigurationElement element)
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
      description: The <xref href="System.Configuration.ConfigurationElement" data-throw-if-not-resolved="false"></xref> to return the key for.
    return:
      type: System.Object
      description: "\nAn <xref href=\"System.Object\" data-throw-if-not-resolved=\"false\"></xref> that acts as the key for the specified <xref href=\"System.Configuration.ConfigurationElement\" data-throw-if-not-resolved=\"false\"></xref>.\n"
    content.vb: Protected Overrides Function GetElementKey(element As ConfigurationElement) As Object
  overload: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.GetElementKey*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.#ctor
  commentId: M:TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.#ctor
  id: '#ctor'
  parent: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection
  langs:
  - csharp
  - vb
  name: ExternalTypesConfigurationElementCollection()
  nameWithType: ExternalTypesConfigurationElementCollection.ExternalTypesConfigurationElementCollection()
  fullName: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.ExternalTypesConfigurationElementCollection()
  type: Constructor
  source:
    path: TimeCockpit.Data
    isExternal: true
  assemblies:
  - TimeCockpit.Data
  namespace: TimeCockpit.Data.Extensibility
  syntax:
    content: public ExternalTypesConfigurationElementCollection()
    content.vb: Public Sub New
  overload: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: TimeCockpit.Data.Extensibility
  commentId: N:TimeCockpit.Data.Extensibility
  isExternal: true
  name: TimeCockpit.Data.Extensibility
  nameWithType: TimeCockpit.Data.Extensibility
  fullName: TimeCockpit.Data.Extensibility
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.CreateNewElement*
  commentId: Overload:TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.CreateNewElement
  isExternal: true
  name: CreateNewElement
  nameWithType: ExternalTypesConfigurationElementCollection.CreateNewElement
  fullName: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.CreateNewElement
- uid: System.Configuration.ConfigurationElement
  isExternal: true
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.GetElementKey*
  commentId: Overload:TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.GetElementKey
  isExternal: true
  name: GetElementKey
  nameWithType: ExternalTypesConfigurationElementCollection.GetElementKey
  fullName: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.GetElementKey
- uid: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.#ctor*
  commentId: Overload:TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.#ctor
  isExternal: true
  name: ExternalTypesConfigurationElementCollection
  nameWithType: ExternalTypesConfigurationElementCollection.ExternalTypesConfigurationElementCollection
  fullName: TimeCockpit.Data.Extensibility.ExternalTypesConfigurationElementCollection.ExternalTypesConfigurationElementCollection
